### ISSUE TITLE
Docsie has suffered a failure (repeatedly); must reload - lost changes

### ISSUE THREAD

**Issue by KarenD1231** [LikaloLLC/docsie#54]
CONSTANTLY getting an error message when app tries to save!

[Screen Shot 2019-07-14 at 8 17 47 AM](https://user-images.githubusercontent.com/52883199/61183483-f19f9b00-a60f-11e9-8603-b6157c89ca3a.png)

Yesterday I was using Firefox, today I'm using Chrome.

## Actual behavior: save fails, app hangs, have to reload (lost changes)

P.S. Typo: "Docsie has suffered a falure".

Please advise - I'm losing lots of time/effort when having to REDO my work repeatedly.
Thanks,
Karen

**Comment by PhilippeTrounev** [comment]
Hello,
 Karen we are really sorry about this bad experience that you are having. Today we released a new release  that should address most of these issue. It can be accessed on the following link.
[https://app.docsie.io/manager/?version=1.6.5](https://app.docsie.io/manager/?version=1.6.5 
). It will become the main release tomorrow. 

We are also working on a new release that will enable realtime collaboration which should make it easy to edit same book from multiple browsers and even collaborate in real time. This is coming in early August. 

Best Regards.
Docsie Team.

**Comment by KarenD1231** [comment]
Thanks for the update - hopefully this stabilizes the app because I'm getting much faster at using it, and hope it'll be my permanent tool for documentation. 
/kd

**Comment by PhilippeTrounev** [comment]
Thank you Karen. Let us know if you are face any other issues and we will be happy to address them. Also if possible let us know if there are any features that you would like us to add, to help improve and speed up your documentation workflow.
